/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2020 UniPro <ugene@unipro.ru>
 * http://ugene.net
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef _U2_GT_TESTS_REGRESSION_SCENARIOS_5001_6000_H_
#define _U2_GT_TESTS_REGRESSION_SCENARIOS_5001_6000_H_

#include <U2Test/UGUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {

#undef GUI_TEST_SUITE
#define GUI_TEST_SUITE "GUITest_regression_scenarios"

GUI_TEST_CLASS_DECLARATION(test_5004)
GUI_TEST_CLASS_DECLARATION(test_5012)
GUI_TEST_CLASS_DECLARATION(test_5012_1)
GUI_TEST_CLASS_DECLARATION(test_5012_2)
GUI_TEST_CLASS_DECLARATION(test_5018)
GUI_TEST_CLASS_DECLARATION(test_5026)
GUI_TEST_CLASS_DECLARATION(test_5027_1)
GUI_TEST_CLASS_DECLARATION(test_5027_2)
GUI_TEST_CLASS_DECLARATION(test_5029)
GUI_TEST_CLASS_DECLARATION(test_5039)
GUI_TEST_CLASS_DECLARATION(test_5052)
GUI_TEST_CLASS_DECLARATION(test_5069)
GUI_TEST_CLASS_DECLARATION(test_5082)
GUI_TEST_CLASS_DECLARATION(test_5090)

GUI_TEST_CLASS_DECLARATION(test_5110)
GUI_TEST_CLASS_DECLARATION(test_5128)
GUI_TEST_CLASS_DECLARATION(test_5130)
GUI_TEST_CLASS_DECLARATION(test_5137)
GUI_TEST_CLASS_DECLARATION(test_5138_1)
GUI_TEST_CLASS_DECLARATION(test_5138_2)
GUI_TEST_CLASS_DECLARATION(test_5199)

GUI_TEST_CLASS_DECLARATION(test_5208)
GUI_TEST_CLASS_DECLARATION(test_5211)
GUI_TEST_CLASS_DECLARATION(test_5216)
GUI_TEST_CLASS_DECLARATION(test_5220)
GUI_TEST_CLASS_DECLARATION(test_5227)
GUI_TEST_CLASS_DECLARATION(test_5231)
GUI_TEST_CLASS_DECLARATION(test_5246)
GUI_TEST_CLASS_DECLARATION(test_5249)
GUI_TEST_CLASS_DECLARATION(test_5252)
GUI_TEST_CLASS_DECLARATION(test_5268)
GUI_TEST_CLASS_DECLARATION(test_5278)
GUI_TEST_CLASS_DECLARATION(test_5295)

GUI_TEST_CLASS_DECLARATION(test_5314)
GUI_TEST_CLASS_DECLARATION(test_5335)
GUI_TEST_CLASS_DECLARATION(test_5346)
GUI_TEST_CLASS_DECLARATION(test_5352)
GUI_TEST_CLASS_DECLARATION(test_5356)
GUI_TEST_CLASS_DECLARATION(test_5360)
GUI_TEST_CLASS_DECLARATION(test_5363_2)
GUI_TEST_CLASS_DECLARATION(test_5367)
GUI_TEST_CLASS_DECLARATION(test_5371)
GUI_TEST_CLASS_DECLARATION(test_5377)
GUI_TEST_CLASS_DECLARATION(test_5382)

GUI_TEST_CLASS_DECLARATION(test_5412)
GUI_TEST_CLASS_DECLARATION(test_5417)
GUI_TEST_CLASS_DECLARATION(test_5425)
GUI_TEST_CLASS_DECLARATION(test_5431)
GUI_TEST_CLASS_DECLARATION(test_5447_1)
GUI_TEST_CLASS_DECLARATION(test_5447_2)
GUI_TEST_CLASS_DECLARATION(test_5447_3)
GUI_TEST_CLASS_DECLARATION(test_5469)
GUI_TEST_CLASS_DECLARATION(test_5492)
GUI_TEST_CLASS_DECLARATION(test_5495)
GUI_TEST_CLASS_DECLARATION(test_5499)

GUI_TEST_CLASS_DECLARATION(test_5517)
GUI_TEST_CLASS_DECLARATION(test_5520_2)
GUI_TEST_CLASS_DECLARATION(test_5550)
GUI_TEST_CLASS_DECLARATION(test_5562_1)
GUI_TEST_CLASS_DECLARATION(test_5562_2)
GUI_TEST_CLASS_DECLARATION(test_5562_3)
GUI_TEST_CLASS_DECLARATION(test_5588)
GUI_TEST_CLASS_DECLARATION(test_5594_1)
GUI_TEST_CLASS_DECLARATION(test_5594_2)
GUI_TEST_CLASS_DECLARATION(test_5594_3)
GUI_TEST_CLASS_DECLARATION(test_5594_4)

GUI_TEST_CLASS_DECLARATION(test_5604)
GUI_TEST_CLASS_DECLARATION(test_5622)
GUI_TEST_CLASS_DECLARATION(test_5636)
GUI_TEST_CLASS_DECLARATION(test_5637)
GUI_TEST_CLASS_DECLARATION(test_5638)
GUI_TEST_CLASS_DECLARATION(test_5659)
GUI_TEST_CLASS_DECLARATION(test_5663)
GUI_TEST_CLASS_DECLARATION(test_5665)
GUI_TEST_CLASS_DECLARATION(test_5681)
GUI_TEST_CLASS_DECLARATION(test_5696)

GUI_TEST_CLASS_DECLARATION(test_5714_1)
GUI_TEST_CLASS_DECLARATION(test_5714_2)
GUI_TEST_CLASS_DECLARATION(test_5714_3)
GUI_TEST_CLASS_DECLARATION(test_5716)
GUI_TEST_CLASS_DECLARATION(test_5718)
GUI_TEST_CLASS_DECLARATION(test_5739)
GUI_TEST_CLASS_DECLARATION(test_5747)
GUI_TEST_CLASS_DECLARATION(test_5750)
GUI_TEST_CLASS_DECLARATION(test_5751)
GUI_TEST_CLASS_DECLARATION(test_5752)
GUI_TEST_CLASS_DECLARATION(test_5753)
GUI_TEST_CLASS_DECLARATION(test_5755)
GUI_TEST_CLASS_DECLARATION(test_5758)
GUI_TEST_CLASS_DECLARATION(test_5759)
GUI_TEST_CLASS_DECLARATION(test_5761)
GUI_TEST_CLASS_DECLARATION(test_5762)
GUI_TEST_CLASS_DECLARATION(test_5769_1)
GUI_TEST_CLASS_DECLARATION(test_5769_2)
GUI_TEST_CLASS_DECLARATION(test_5770)
GUI_TEST_CLASS_DECLARATION(test_5773)
GUI_TEST_CLASS_DECLARATION(test_5775)
GUI_TEST_CLASS_DECLARATION(test_5781)
GUI_TEST_CLASS_DECLARATION(test_5783)
GUI_TEST_CLASS_DECLARATION(test_5786_1)
GUI_TEST_CLASS_DECLARATION(test_5786_2)
GUI_TEST_CLASS_DECLARATION(test_5786_3)
GUI_TEST_CLASS_DECLARATION(test_5789_1)
GUI_TEST_CLASS_DECLARATION(test_5789_2)
GUI_TEST_CLASS_DECLARATION(test_5790)
GUI_TEST_CLASS_DECLARATION(test_5798_1)
GUI_TEST_CLASS_DECLARATION(test_5798_2)
GUI_TEST_CLASS_DECLARATION(test_5798_3)
GUI_TEST_CLASS_DECLARATION(test_5798_4)
GUI_TEST_CLASS_DECLARATION(test_5798_5)

GUI_TEST_CLASS_DECLARATION(test_5815)
GUI_TEST_CLASS_DECLARATION(test_5818_1)
GUI_TEST_CLASS_DECLARATION(test_5818_2)
GUI_TEST_CLASS_DECLARATION(test_5832)
GUI_TEST_CLASS_DECLARATION(test_5833)
GUI_TEST_CLASS_DECLARATION(test_5837)
GUI_TEST_CLASS_DECLARATION(test_5840)
GUI_TEST_CLASS_DECLARATION(test_5847)
GUI_TEST_CLASS_DECLARATION(test_5849)
GUI_TEST_CLASS_DECLARATION(test_5851)
GUI_TEST_CLASS_DECLARATION(test_5853)
GUI_TEST_CLASS_DECLARATION(test_5854)
GUI_TEST_CLASS_DECLARATION(test_5855)
GUI_TEST_CLASS_DECLARATION(test_5872)
GUI_TEST_CLASS_DECLARATION(test_5898)
GUI_TEST_CLASS_DECLARATION(test_5903)
GUI_TEST_CLASS_DECLARATION(test_5905)
GUI_TEST_CLASS_DECLARATION(test_5947)
GUI_TEST_CLASS_DECLARATION(test_5948)
GUI_TEST_CLASS_DECLARATION(test_5950)
GUI_TEST_CLASS_DECLARATION(test_5970)
GUI_TEST_CLASS_DECLARATION(test_5972_1)
GUI_TEST_CLASS_DECLARATION(test_5972_2)

#undef GUI_TEST_SUITE

}    // namespace GUITest_regression_scenarios

}    // namespace U2

#endif    // _U2_GT_TESTS_REGRESSION_SCENARIOS_5001_6000_H_
