swps3: debug.c File Reference
debug.c File Reference
Routines for error reporting.
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
Functions
void error (const char *str,...)
printf-like function for critical error reporting.
void warning (const char *str,...)
printf-like function for noncritical error reporting.
Detailed Description
Routines for error reporting.
Definition in file debug.c.
Function Documentation
void error (const char * str, ...)
printf-like function for critical error reporting.
Reports a message to stderr and terminates the program.
Parameters
str A format string.
Definition at line 40 of file debug.c.
Referenced by swps3_alignmentByteSPE(), swps3_alignmentFloatSPE(), swps3_alignmentShortSPE(), swps3_loadProfileByte(), swps3_loadProfileFloat(), swps3_loadProfileShort(), swps3_openLib(), swps3_readDMatrix(), swps3_readNextSequence(), swps3_readSBMatrix(), and swps3_translateSequence().
void warning (const char * str, ...)
printf-like function for noncritical error reporting.
Reports a message to stderr without terminating the program.
Parameters
str A format string.
Definition at line 56 of file debug.c.
Referenced by swps3_alignmentByteSPE(), swps3_alignmentFloatSPE(), swps3_alignmentShortSPE(), and swps3_readNextSequence().