swps3: DynProgr_SPE_main.c File Reference
DynProgr_SPE_main.c File Reference
Main routine and message handling on the SPE.
#include <spu_mfcio.h>
#include "DynProgr_SPE.h"
#include "DynProgr_SPE_functions.h"
#include <stdio.h>
#include "matrix.h"
Macros
#define max(a, b) (((a)>(b))?(a):(b))
#define min(a, b) (((a)<(b))?(a):(b))
Functions
static int8_t mainMemory[TOTAL_MEMORY] __attribute__ ((__aligned__(16)))
void * alloc (int size)
int handleCommand (ppu_addr_t program_data_ea)
int main (uint64_t spe_id, ppu_addr_t program_data_ea, ppu_addr_t env)
int memRemaining ()
void reset ()
Variables
static int allocated = 0
static int datatype = -1
Detailed Description
Main routine and message handling on the SPE.
Definition in file DynProgr_SPE_main.c.
Macro Definition Documentation
#define max (a, b) (((a)>(b))?(a):(b))
Definition at line 38 of file DynProgr_SPE_main.c.
Referenced by handleCommand(), SPECreateProfile(), swps3_alignmentByteSPE(), swps3_alignmentFloatSPE(), and swps3_alignmentShortSPE().
#define min (a, b) (((a)<(b))?(a):(b))
Definition at line 37 of file DynProgr_SPE_main.c.
Referenced by handleCommand(), SPECreateProfile(), swps3_alignmentByteSPE(), swps3_alignmentFloatSPE(), and swps3_alignmentShortSPE().
Function Documentation
static int8_t mainMemory [ TOTAL_MEMORY ] __attribute__ ((__aligned__(16))) static
void* alloc (int size)
Definition at line 43 of file DynProgr_SPE_main.c.
References ALIGN16, allocated, and TOTAL_MEMORY.
Referenced by handleCommand().
int handleCommand (ppu_addr_t program_data_ea)
Definition at line 57 of file DynProgr_SPE_main.c.
References __ALIGNED__, ALIGN16, alloc(), blockSize, blockStart, createProfile, dataSize, datatype, delS, dynProgLocal, fixedDel, incDel, loadOpt, ls1, ls2, MATRIX_DIM, max, MAX_TRANSFER, maxDbLen, maxS, memRemaining(), min, mn, mx, profile, rD, remote_profile, reset(), s1, s2, simi, SPE_CMD_ALIGN, SPE_CMD_CREATE_PROFILE, SPE_CMD_GET_PROFILE, SPE_CMD_INIT, SPE_CMD_PUT_PROFILE, and storeOpt.
Referenced by main().
int main (uint64_t spe_id, ppu_addr_t program_data_ea, ppu_addr_t env)
Definition at line 253 of file DynProgr_SPE_main.c.
References handleCommand().
int memRemaining ()
Definition at line 49 of file DynProgr_SPE_main.c.
References allocated, and TOTAL_MEMORY.
Referenced by handleCommand().
void reset ()
Definition at line 52 of file DynProgr_SPE_main.c.
Referenced by handleCommand().
Variable Documentation
int allocated = 0 static
Definition at line 41 of file DynProgr_SPE_main.c.
Referenced by alloc(), and memRemaining().
int datatype = -1 static
Definition at line 42 of file DynProgr_SPE_main.c.
Referenced by handleCommand().