swps3: DynProgr_sse_byte.h File Reference
DynProgr_sse_byte.h File Reference
Profile generation and alignment for packed byte vectors on SSE2.
#include "swps3.h"
#include "matrix.h"
#include <xmmintrin.h>
Classes
struct ProfileByte
Functions
double swps3_alignmentByteSSE (ProfileByte *query, const char *db, int dbLen, Options *options)
ProfileByte * swps3_createProfileByteSSE (const char *query, int queryLen, SBMatrix matrix)
Creates a profile with unsigned 8 bit integers.
void swps3_freeProfileByteSSE (ProfileByte *profile)
Detailed Description
Profile generation and alignment for packed byte vectors on SSE2.
Definition in file DynProgr_sse_byte.h.
Function Documentation
double swps3_alignmentByteSSE (ProfileByte * query, const char * db, int dbLen, Options * options)
Definition at line 221 of file DynProgr_sse_byte.c.
References ProfileByte::bias, debug, Options::gapExt, Options::gapOpen, ProfileByte::len, LIKELY, ProfileByte::loadOpt, loadOpt, ProfileByte::profile, ProfileByte::rD, rD, ProfileByte::storeOpt, storeOpt, swps3_alignmentByteSSE_lin(), and UNLIKELY.
Referenced by main().
ProfileByte* swps3_createProfileByteSSE (const char * query, int queryLen, SBMatrix matrix)
Creates a profile with unsigned 8 bit integers.
Definition at line 40 of file DynProgr_sse_byte.c.
References ProfileByte::bias, ProfileByte::data, debug, ProfileByte::len, ProfileByte::loadOpt, MATRIX_DIM, PAGE_ALIGN, ProfileByte::profile, profile, ProfileByte::rD, and ProfileByte::storeOpt.
Referenced by main().
void swps3_freeProfileByteSSE (ProfileByte * profile)
Definition at line 376 of file DynProgr_sse_byte.c.
Referenced by main().