swps3: DynProgr_sse_short.c File Reference
DynProgr_sse_short.c File Reference
Profile generation and alignment for packed short vectors on SSE2.
#include "DynProgr_sse_short.h"
#include <stdio.h>
#include <unistd.h>
#include <float.h>
Macros
#define PAGE_ALIGN(x) (((size_t)(x)+sysconf(_SC_PAGESIZE)-1)&~(sysconf(_SC_PAGESIZE)-1))
Functions
double swps3_alignmentShort2SSE (ProfileShort *query, const char *db, int dbLen, Options *options)
EXPORT double swps3_alignmentShortSSE (ProfileShort *query, const char *db, int dbLen, Options *options)
EXPORT double swps3_alignmentShortSSE_lin (ProfileShort *query, const char *db, int dbLen, Options *options)
EXPORT ProfileShort * swps3_createProfileShortSSE (const char *query, int queryLen, SBMatrix matrix)
EXPORT void swps3_freeProfileShortSSE (ProfileShort *profile)
Detailed Description
Profile generation and alignment for packed short vectors on SSE2.
Definition in file DynProgr_sse_short.c.
Macro Definition Documentation
#define PAGE_ALIGN (x) (((size_t)(x)+sysconf(_SC_PAGESIZE)-1)&~(sysconf(_SC_PAGESIZE)-1))
Definition at line 35 of file DynProgr_sse_short.c.
Referenced by swps3_createProfileShortSSE().
Function Documentation
double swps3_alignmentShort2SSE (ProfileShort * query, const char * db, int dbLen, Options * options)
Definition at line 206 of file DynProgr_sse_short.c.
References ProfileShort::bias, Options::gapExt, Options::gapOpen, ProfileShort::len, LIKELY, ProfileShort::loadOpt, loadOpt, ProfileShort::profile, ProfileShort::rD, rD, ProfileShort::storeOpt, storeOpt, swps3_alignmentShortSSE_lin(), and UNLIKELY.
EXPORT double swps3_alignmentShortSSE (ProfileShort * query, const char * db, int dbLen, Options * options)
Definition at line 390 of file DynProgr_sse_short.c.
References ProfileShort::bias, Options::gapExt, Options::gapOpen, ProfileShort::len, LIKELY, ProfileShort::loadOpt, loadOpt, ProfileShort::profile, ProfileShort::rD, rD, ProfileShort::storeOpt, storeOpt, swps3_alignmentShortSSE_lin(), and UNLIKELY.
Referenced by main().
EXPORT double swps3_alignmentShortSSE_lin (ProfileShort * query, const char * db, int dbLen, Options * options)
Definition at line 69 of file DynProgr_sse_short.c.
References ProfileShort::bias, Options::gapOpen, ProfileShort::len, LIKELY, ProfileShort::loadOpt, loadOpt, ProfileShort::profile, ProfileShort::storeOpt, storeOpt, and UNLIKELY.
Referenced by swps3_alignmentShort2SSE(), and swps3_alignmentShortSSE().
EXPORT ProfileShort* swps3_createProfileShortSSE (const char * query, int queryLen, SBMatrix matrix)
Definition at line 36 of file DynProgr_sse_short.c.
References ProfileShort::bias, ProfileShort::data, ProfileShort::len, ProfileShort::loadOpt, MATRIX_DIM, PAGE_ALIGN, ProfileShort::profile, profile, ProfileShort::rD, and ProfileShort::storeOpt.
Referenced by main().
EXPORT void swps3_freeProfileShortSSE (ProfileShort * profile)
Definition at line 542 of file DynProgr_sse_short.c.
Referenced by main().