swps3: DynProgr_sse_short.h File Reference
DynProgr_sse_short.h File Reference
Profile generation and alignment for packed short vectors on SSE2.
#include "swps3.h"
#include "matrix.h"
#include <xmmintrin.h>
Classes
struct ProfileShort
Functions
double swps3_alignmentShortSSE (ProfileShort *query, const char *db, int dbLen, Options *options)
ProfileShort * swps3_createProfileShortSSE (const char *query, int queryLen, SBMatrix matrix)
void swps3_freeProfileShortSSE (ProfileShort *profile)
Detailed Description
Profile generation and alignment for packed short vectors on SSE2.
Definition in file DynProgr_sse_short.h.
Function Documentation
double swps3_alignmentShortSSE (ProfileShort * query, const char * db, int dbLen, Options * options)
Definition at line 390 of file DynProgr_sse_short.c.
References ProfileShort::bias, Options::gapExt, Options::gapOpen, ProfileShort::len, LIKELY, ProfileShort::loadOpt, loadOpt, ProfileShort::profile, ProfileShort::rD, rD, ProfileShort::storeOpt, storeOpt, swps3_alignmentShortSSE_lin(), and UNLIKELY.
Referenced by main().
ProfileShort* swps3_createProfileShortSSE (const char * query, int queryLen, SBMatrix matrix)
Definition at line 36 of file DynProgr_sse_short.c.
References ProfileShort::bias, ProfileShort::data, ProfileShort::len, ProfileShort::loadOpt, MATRIX_DIM, PAGE_ALIGN, ProfileShort::profile, profile, ProfileShort::rD, and ProfileShort::storeOpt.
Referenced by main().
void swps3_freeProfileShortSSE (ProfileShort * profile)
Definition at line 542 of file DynProgr_sse_short.c.
Referenced by main().