swps3: DynProgr_sse_byte.c File Reference
DynProgr_sse_byte.c File Reference
Profile generation and alignment for packed byte vectors on SSE2.
#include "DynProgr_sse_byte.h"
#include "debug.h"
#include <unistd.h>
#include <stdio.h>
#include <float.h>
Macros
#define PAGE_ALIGN(x) (((size_t)(x)+sysconf(_SC_PAGESIZE)-1)&~(sysconf(_SC_PAGESIZE)-1))
Functions
EXPORT double swps3_alignmentByteSSE (ProfileByte *query, const char *db, int dbLen, Options *options)
EXPORT double swps3_alignmentByteSSE_lin (ProfileByte *query, const char *db, int dbLen, Options *options)
EXPORT ProfileByte * swps3_createProfileByteSSE (const char *query, int queryLen, SBMatrix matrix)
Creates a profile with unsigned 8 bit integers.
EXPORT void swps3_freeProfileByteSSE (ProfileByte *profile)
Detailed Description
Profile generation and alignment for packed byte vectors on SSE2.
Definition in file DynProgr_sse_byte.c.
Macro Definition Documentation
#define PAGE_ALIGN (x) (((size_t)(x)+sysconf(_SC_PAGESIZE)-1)&~(sysconf(_SC_PAGESIZE)-1))
Definition at line 36 of file DynProgr_sse_byte.c.
Referenced by swps3_createProfileByteSSE().
Function Documentation
EXPORT double swps3_alignmentByteSSE (ProfileByte * query, const char * db, int dbLen, Options * options)
Definition at line 221 of file DynProgr_sse_byte.c.
References ProfileByte::bias, debug, Options::gapExt, Options::gapOpen, ProfileByte::len, LIKELY, ProfileByte::loadOpt, loadOpt, ProfileByte::profile, ProfileByte::rD, rD, ProfileByte::storeOpt, storeOpt, swps3_alignmentByteSSE_lin(), and UNLIKELY.
Referenced by main().
EXPORT double swps3_alignmentByteSSE_lin (ProfileByte * query, const char * db, int dbLen, Options * options)
Definition at line 78 of file DynProgr_sse_byte.c.
References ProfileByte::bias, debug, Options::gapOpen, ProfileByte::len, LIKELY, ProfileByte::loadOpt, loadOpt, ProfileByte::profile, ProfileByte::storeOpt, storeOpt, and UNLIKELY.
Referenced by swps3_alignmentByteSSE().
EXPORT ProfileByte* swps3_createProfileByteSSE (const char * query, int queryLen, SBMatrix matrix)
Creates a profile with unsigned 8 bit integers.
Definition at line 40 of file DynProgr_sse_byte.c.
References ProfileByte::bias, ProfileByte::data, debug, ProfileByte::len, ProfileByte::loadOpt, MATRIX_DIM, PAGE_ALIGN, ProfileByte::profile, profile, ProfileByte::rD, and ProfileByte::storeOpt.
Referenced by main().
EXPORT void swps3_freeProfileByteSSE (ProfileByte * profile)
Definition at line 376 of file DynProgr_sse_byte.c.
Referenced by main().