swps3: DynProgr_scalar.h File Reference
DynProgr_scalar.h File Reference
Scalar platform independent alignment routine.
#include "swps3.h"
Functions
double swps3_alignScalar (const DMatrix matrix, const char *s1, int ls1, const char *s2, int ls2, Options *options)
Detailed Description
Scalar platform independent alignment routine.
Definition in file DynProgr_scalar.h.
Function Documentation
double swps3_alignScalar (const DMatrix matrix, const char * s1, int ls1, const char * s2, int ls2, Options * options)
Definition at line 36 of file DynProgr_scalar.c.
References Options::gapExt, Options::gapOpen, INFINITY, ls1, ls2, MATRIX_DIM, MAX_SEQ_LENGTH, and Options::threshold.
Referenced by main(), swps3_alignmentByteSPE(), swps3_alignmentFloatSPE(), and swps3_alignmentShortSPE().