swps3: DynProgr_scalar.c File Reference
DynProgr_scalar.c File Reference
Scalar alignment routine.
#include <sys/types.h>
#include "swps3.h"
#include "debug.h"
#include "matrix.h"
Macros
#define INFINITY (1.0/0.0)
Functions
EXPORT double swps3_alignScalar (const DMatrix matrix, const char *s1, int ls1, const char *s2, int ls2, Options *options)
Detailed Description
Scalar alignment routine.
Definition in file DynProgr_scalar.c.
Macro Definition Documentation
#define INFINITY (1.0/0.0)
Definition at line 35 of file DynProgr_scalar.c.
Referenced by swps3_alignScalar().
Function Documentation
EXPORT double swps3_alignScalar (const DMatrix matrix, const char * s1, int ls1, const char * s2, int ls2, Options * options)
Definition at line 36 of file DynProgr_scalar.c.
References Options::gapExt, Options::gapOpen, INFINITY, ls1, ls2, MATRIX_DIM, MAX_SEQ_LENGTH, and Options::threshold.
Referenced by main(), swps3_alignmentByteSPE(), swps3_alignmentFloatSPE(), and swps3_alignmentShortSPE().