swps3: DynProgr_PPU.h File Reference
DynProgr_PPU.h File Reference
PPU frontend to the alignment routines on the SPU.
#include "swps3.h"
#include "matrix.h"
#include "DynProgr_SPE.h"
Functions
double swps3_alignmentByteSPE (const SBMatrix matrix, const char *query, int queryLen, const char *db, int dbLen, Options *options)
double swps3_alignmentFloatSPE (const SBMatrix matrix, const char *query, int queryLen, const char *db, int dbLen, Options *options)
double swps3_alignmentProfileSPE (const char *db, int dbLen)
Profile must have been loaded before!
double swps3_alignmentShortSPE (const SBMatrix matrix, const char *query, int queryLen, const char *db, int dbLen, Options *options)
SPEProfile * swps3_createProfileBytePPU (const char *query, int queryLen, const SBMatrix matrix, int maxDbLen)
SPEProfile * swps3_createProfileFloatPPU (const char *query, int queryLen, const SBMatrix matrix, int maxDbLen)
SPEProfile * swps3_createProfileShortPPU (const char *query, int queryLen, const SBMatrix matrix, int maxDbLen)
void swps3_freeProfilePPU (SPEProfile *profile)
void swps3_loadProfileByte (SPEProfile *profile, int maxDbLen, Options *options)
void swps3_loadProfileFloat (SPEProfile *profile, int maxDbLen, Options *options)
void swps3_loadProfileShort (SPEProfile *profile, int maxDbLen, Options *options)
Detailed Description
PPU frontend to the alignment routines on the SPU.
Definition in file DynProgr_PPU.h.
Function Documentation
double swps3_alignmentByteSPE (const SBMatrix matrix, const char * query, int queryLen, const char * db, int dbLen, Options * options)
Definition at line 217 of file DynProgr_PPU.c.
References error(), Options::gapExt, Options::gapOpen, MATRIX_DIM, max, MAX, min, MIN, SPE_DATA_INT8, SPEAlign(), SPECreateProfile(), SPEInit(), swps3_alignScalar(), and warning().
Referenced by main().
double swps3_alignmentFloatSPE (const SBMatrix matrix, const char * query, int queryLen, const char * db, int dbLen, Options * options)
Definition at line 279 of file DynProgr_PPU.c.
References __ALIGNED__, error(), Options::gapExt, Options::gapOpen, MATRIX_DIM, max, MAX, min, MIN, simi, SPE_DATA_FLOAT, SPEAlign(), SPECreateProfile(), SPEInit(), swps3_alignScalar(), and warning().
double swps3_alignmentProfileSPE (const char * db, int dbLen)
Profile must have been loaded before!
Definition at line 314 of file DynProgr_PPU.c.
References SPEAlign().
Referenced by main().
double swps3_alignmentShortSPE (const SBMatrix matrix, const char * query, int queryLen, const char * db, int dbLen, Options * options)
Definition at line 247 of file DynProgr_PPU.c.
References __ALIGNED__, error(), Options::gapExt, Options::gapOpen, MATRIX_DIM, max, MAX, min, MIN, simi, SPE_DATA_INT16, SPEAlign(), SPECreateProfile(), SPEInit(), swps3_alignScalar(), and warning().
Referenced by main().
SPEProfile* swps3_createProfileBytePPU (const char * query, int queryLen, const SBMatrix matrix, int maxDbLen)
Definition at line 359 of file DynProgr_PPU.c.
Referenced by main().
SPEProfile* swps3_createProfileFloatPPU (const char * query, int queryLen, const SBMatrix matrix, int maxDbLen)
Definition at line 373 of file DynProgr_PPU.c.
Referenced by main().
SPEProfile* swps3_createProfileShortPPU (const char * query, int queryLen, const SBMatrix matrix, int maxDbLen)
Definition at line 366 of file DynProgr_PPU.c.
Referenced by main().
void swps3_freeProfilePPU (SPEProfile * profile)
Definition at line 379 of file DynProgr_PPU.c.
References SPEProfile::addr.
Referenced by main().
void swps3_loadProfileByte (SPEProfile * profile, int maxDbLen, Options * options)
Definition at line 325 of file DynProgr_PPU.c.
References error(), SPE_DATA_INT8, SPEGetProfile(), and SPEInit().
Referenced by main().
void swps3_loadProfileFloat (SPEProfile * profile, int maxDbLen, Options * options)
Definition at line 347 of file DynProgr_PPU.c.
References error(), SPE_DATA_FLOAT, SPEGetProfile(), and SPEInit().
void swps3_loadProfileShort (SPEProfile * profile, int maxDbLen, Options * options)
Definition at line 336 of file DynProgr_PPU.c.
References error(), SPE_DATA_INT16, SPEGetProfile(), and SPEInit().
Referenced by main().