swps3: fasta.c File Reference
fasta.c File Reference
Routines for reading FASTA databases.
#include "fasta.h"
#include "swps3.h"
#include "debug.h"
#include <stdlib.h>
#include <string.h>
#include <errno.h>
Functions
EXPORT void swps3_closeLib (FastaLib *lib)
EXPORT char * swps3_getSequenceName (FastaLib *lib)
EXPORT FastaLib * swps3_openLib (char *filename)
EXPORT char * swps3_readNextSequence (FastaLib *lib, int *len)
EXPORT void swps3_translateSequence (char *sequence, int seqLen, char table[256])
Detailed Description
Routines for reading FASTA databases.
Definition in file fasta.c.
Function Documentation
EXPORT void swps3_closeLib (FastaLib * lib)
Definition at line 97 of file fasta.c.
References FastaLib::fp.
Referenced by main().
EXPORT char* swps3_getSequenceName (FastaLib * lib)
Definition at line 94 of file fasta.c.
References FastaLib::name.
Referenced by main().
EXPORT FastaLib* swps3_openLib (char * filename)
Definition at line 40 of file fasta.c.
References error(), FastaLib::fp, FastaLib::name, and swps3_readNextSequence().
Referenced by main().
EXPORT char* swps3_readNextSequence (FastaLib * lib, int * len)
Definition at line 61 of file fasta.c.
References FastaLib::data, error(), FastaLib::fp, FastaLib::name, swps3_translateSequence(), and warning().
Referenced by main(), and swps3_openLib().
EXPORT void swps3_translateSequence (char * sequence, int seqLen, char table[256])
Definition at line 101 of file fasta.c.
References error(), and MATRIX_DIM.
Referenced by swps3_readNextSequence().